version: "3"
services:
  kudu-master-1:
    image: apache/kudu:latest
    network_mode: host   
    command: ["master"]
    environment:
     - KUDU_MASTERS=127.0.0.1:7051,127.0.0.1:7052,127.0.0.1:7053
     - >
       MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
       --rpc_bind_addresses=0.0.0.0:7051
       --webserver_port=8151
       --use_hybrid_clock=false
  kudu-master-2:
    image: apache/kudu:latest
    network_mode: host  
    command: ["master"]
    environment:
     - KUDU_MASTERS=127.0.0.1:7051,127.0.0.1:7052,127.0.0.1:7053
     - >
       MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
       --rpc_bind_addresses=0.0.0.0:7052
       --webserver_port=8152
       --use_hybrid_clock=false      
  kudu-master-3:
    image: apache/kudu:latest
    network_mode: host   
    command: ["master"]
    environment:
     - KUDU_MASTERS=127.0.0.1:7051,127.0.0.1:7052,127.0.0.1:7053
     - >
       MASTER_ARGS=--fs_wal_dir=/var/lib/kudu/master
       --rpc_bind_addresses=0.0.0.0:7053
       --webserver_port=8153
       --use_hybrid_clock=false      
  kudu-tserver:
    image: apache/kudu:latest
    network_mode: host
    depends_on:
      - kudu-master-1
      - kudu-master-2
      - kudu-master-3
    command: ["tserver"]
    environment:
     - KUDU_MASTERS=127.0.0.1:7051,127.0.0.1:7052,127.0.0.1:7053
     - >
       TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
       --rpc_bind_addresses=0.0.0.0:7150
       --webserver_port=8250
  kudu-tserver-2:
    image: apache/kudu:latest
    network_mode: host
    depends_on:
      - kudu-master-1
      - kudu-master-2
      - kudu-master-3
    command: ["tserver"]
    environment:
     - KUDU_MASTERS=127.0.0.1:7051,127.0.0.1:7052,127.0.0.1:7053
     - >
       TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
       --rpc_bind_addresses=0.0.0.0:7152
       --webserver_port=8252
  kudu-tserver-3:
    image: apache/kudu:latest
    network_mode: host
    depends_on:
      - kudu-master-1
      - kudu-master-2
      - kudu-master-3
    command: ["tserver"]
    environment:
     - KUDU_MASTERS=127.0.0.1:7051,127.0.0.1:7052,127.0.0.1:7053
     - >
       TSERVER_ARGS=--fs_wal_dir=/var/lib/kudu/tserver
       --rpc_bind_addresses=0.0.0.0:7153
       --webserver_port=8253
